@access-token =eyJ0eXAiOi.....
# Complete Sample
# @spn_Id=7acdd580-.....
@spn_Id=e7f751ac-9edb....
@applications_Id=91e4e9d8-e0c....
###

https://graph.microsoft.com/beta/ServicePrincipals/{{spn_Id}}/claimsPolicy?$select=claims
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/ServicePrincipals
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/ServicePrincipals/{{spn_Id}}/claimsPolicy
Authorization: Bearer {{access-token}}

###
GET https://graph.microsoft.com/v1.0/servicePrincipals/{{spn_Id}}/synchronization/jobs/
Authorization: Bearer {{access-token}}
###

GET https://graph.microsoft.com/v1.0/servicePrincipals/{{spn_Id}}/synchronization/jobs/scim.7bf7ca0220a64cc7a35d8fa9c5fd4529.a9f97dcd-9abb-4322-96e1-01e483d6e88f/schema
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/ServicePrincipals/{{spn_Id}}/claimsPolicy?$select=audienceOverride,claims
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/policies/claimsMappingPolicies
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/ServicePrincipals/{{spn_Id}}/claimsPolicy
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/beta/ServicePrincipals/{{spn_Id}}
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/v1.0/applications/
Authorization: Bearer {{access-token}}

###

https://graph.microsoft.com/v1.0/applications/{{applications_Id}}/
Authorization: Bearer {{access-token}}

###

GET https://graph.microsoft.com/v1.0/applications/{{applications_Id}}
Authorization: Bearer {{access-token}}

###

GET https://graph.microsoft.com/v1.0/applications/{{applications_Id}}
Authorization: Bearer {{access-token}}

###

GET https://graph.microsoft.com/v1.0/applications?$select=id,displayName,appId
Authorization: Bearer {{access-token}}

###
GET https://graph.microsoft.com/v1.0/applications(appId='{{applications_Id}}')
Authorization: Bearer {{access-token}}

###
GET https://microsoftscimwebhostsamplexxx.azurewebsites.net/scim/Users?filter=userName+eq+%229ee3d4fe-34f2-43cb-9b21-8e2c9c9d63a3%22
Authorization: Bearer {{access-token}}